### ISSUE TITLE
`onScroll` cause list to be blank after few items

### ISSUE THREAD

**Issue by huextrat** [LegendApp/legend-list#14]
When we implement the `onScroll` listener, when we scroll after 5 items, the items in the list are no longer rendered at all. This must be due to the onScroll, since if you delete it, the list is rendered correctly.

Repro branch : https://github.com/huextrat/legend-list/tree/chore/onScroll-issue

This simple change is enough to repro the issue: https://github.com/huextrat/legend-list/commit/afcab40b788152444aec3dc14887a0d9d236f71e

I don't have much time to look at this in the next few days, so if anyone wants to take a look and make a proposal to fix it.

Screenshot: 
![Simulator Screenshot - iPhone 16 - 2024-11-23 at 18 40 44](https://github.com/user-attachments/assets/18fd5f9d-0da8-4fe2-9fb0-5cb9a56df6a4)

**Comment by jmeistrich** [comment]
Thanks for catching that! I thought I'd fixed it already but found the fix in a stash 😅

It was passing in `{...rest}` after all of the local props so it was overriding all of our scroll handling, breaking everything 😂

Fixed in 0.3.1.
