### ISSUE TITLE
Expose FlatList compatible ref interface.

### ISSUE THREAD

**Issue by mbilenko-florio** [LegendApp/legend-list#17]
Currently underlying ScrollView is forwarded as LegendList ref. FlatList on other hand, has pretty distinct interface for the ref value. https://reactnative.dev/docs/flatlist#methods

<img width="224" alt="Screenshot 2024-11-24 at 11 25 44" src="https://github.com/user-attachments/assets/2cb62c5f-5c95-4207-8cd8-05108fd3e860">

And scrollview ref is returned as getNativeScrollRef()  result. 

This can be implemented with useImperativeHandle with code roughly like this
```
React.useImperativeHandle(forwardedRef, () => {
            return {
                getScrollableNode: () => internalRef.current,
                scrollTo: internalRef.current!.scrollTo,
                scrollToEnd: internalRef.current!.scrollToEnd,
                flashScrollIndicators: internalRef.current!.flashScrollIndicators,
                scrollToIndex: (params) => {
                    const offsetObj = calculateInitialOffset(params.index);     
                    const offset = horizontal ? { x: offsetObj, y: 0 } : { x: 0, y: offsetObj };
                    internalRef.current!.scrollTo(offset);
                },
                ....
            };
        }, []);
```

**Comment by jmeistrich** [comment]
Yes, agreed. We definitely need that. Would you like to PR it?

**Comment by mbilenko-florio** [comment]
Yep, will try to work on it.

**Comment by jmeistrich** [comment]
@mbilenko-florio FYI I just committed a pretty big refactor so you might want to pull first :)

**Comment by mbilenko-florio** [comment]
> @mbilenko-florio FYI I just committed a pretty big refactor so you might want to pull first :)

@jmeistrich Did you undo big refactor now? Is there a change of it coming back?

**Comment by jmeistrich** [comment]
Sorry, yes I did undo it just a couple hours ago. I was doing perf testing and found it made perf significantly worse. But I left it in the `refactor` branch so if you did a lot of changes on top of that, you could PR to that branch and I can cherry pick the changes back into main. Sorry about that!

**Comment by jmeistrich** [comment]
Just merged it, thank you!
