### ISSUE TITLE
Add Eslint & TypeScript-Eslint for formatting code

### ISSUE THREAD

**Issue by sant3001** [LegendApp/legend-list#20]
## Motivation

Linting is a common pattern for most modern JS projects. This can be added to the project with the latest standards.

## Optionally

Eslint also has an integration with Prettier: [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier). This would be 
a nice to have as well.

**Comment by sant3001** [comment]
I will contribute with an upcoming PR.

**Comment by jmeistrich** [comment]
I decided to go with Biome from an earlier PR (https://github.com/LegendApp/legend-list/pull/10) for that. Thanks for the PR though!
