### ISSUE TITLE
Are these memoizations necessary?

### ISSUE THREAD

**Issue by nandorojo** [LegendApp/legend-list#36]
https://github.com/LegendApp/legend-list/blob/c9ef75e10c118830bd06be92c7106cc55666e54b/src/LegendList.tsx#L78-L84

I predict that these memoizations hurt performance rather than help. They are using a JSON.stringify check which can be expensive for large objects, requires keeping the result in memory and comparing it, and then, to make things worse, when passed to the underlying component, the style is turned into an array, breaking any gains earned by the prior memoization:

https://github.com/LegendApp/legend-list/blob/c9ef75e10c118830bd06be92c7106cc55666e54b/src/LegendList.tsx#L693

In case there's something I'm missing (which is possible!) I'd suggest removing these, unless I'm missing something?

**Comment by jmeistrich** [comment]
Hahaha yes, good point 😂. I had done that `[style]` while testing something and forgot to revert it. 

The purpose of those memos is to reduce the number of times ListComponent has to render, so if only `data` changes then it shouldn't re-render ListComponent. But there's probably a better way to do this than stringifying...

**Comment by nandorojo** [comment]
i would just forward down the props as-is, unless there's some good reason for flattening. but the cost of this stringify + memoization is almost certainly going to be worse than the list re-rendering. the list items should be granularly memoized separate from the parent styles of the list itself to avoid this mattering.

**Comment by jmeistrich** [comment]
Oh ha yeah, they're not even doing anything anymore 😅. In earlier prototypes I was playing with setting styles to compensate for adjusting scroll, but went a different direction. So I think I can just remove all of that 👍

**Comment by jmeistrich** [comment]
I removed all that in the `maintainVisibleContentPosition` branch I'm working in now. Thank you for catching that!
