### ISSUE TITLE
Discussion: offscreen item measurement method

### ISSUE THREAD

**Issue by mbilenko-florio** [LegendApp/legend-list#50]
@jmeistrich  When working on the infinite list, i've found issue with the offscreen measurement method of the element. For my case making element invisible yielded much better results. 

Problem happends, when I remove fixed width from cards-renderitem.tsx. 
```
   itemOuterContainer: {
        paddingVertical: 8,
        paddingHorizontal: 8,
        //width: 380,
        //marginLeft: 6,
    },
```
When using offscreen measurement, there are lot more onLayouts happening then in case of invisible measurement.

Offscreen measurement(click to see video, artifacts visible):
[![OFFSCREEN](https://img.youtube.com/vi/HVmp_UyOFm0/0.jpg)](https://www.youtube.com/watch?v=HVmp_UyOFm0?rel=0)

Invisible measurement:
[![Invisible](https://img.youtube.com/vi/ojC-ZYE1ywU/0.jpg)](https://www.youtube.com/watch?v=ojC-ZYE1ywU?rel=0)

Demo can be seen there: https://github.com/mbilenko-florio/legend-list/tree/demo/offscreen-vs-invisible

Measurement method can be easily changed in the Container.tsx
``` 
type MeasureMethod = "offscreen" | "invisible";
const MEASURE_METHOD: MeasureMethod = "offscreen";
```
Can we improve offscreen measurement method to have less onLayouts, should we add invisible method as additional prop to the LegendList or urge user to hard code element width to the current screen width?

**Comment by jmeistrich** [comment]
Just remove the off screen layout method. It was a workaround to another issue that should be solved a different way anyway.
