### ISSUE TITLE
[Web][0.5.8] Uncaught TypeError: (0 , _index.useAnimatedValue) is not a function

### ISSUE THREAD

**Issue by a-eid** [LegendApp/legend-list#51]
unable to get legend list to run on web. 

<img width="650" alt="Screenshot 2024-12-27 at 5 43 58 PM" src="https://github.com/user-attachments/assets/afc5ece4-2eb6-4377-b58b-9f8b4944bce4" />

**Comment by jmeistrich** [comment]
Ah apparently that is not supported in react-native-web, though it look like they just merged a PR adding it.

I added a polyfill for it, so it should work now in 0.5.9.

Thanks for the report!

**Comment by a-eid** [comment]
`0.5.9` indeed fixes the issue. thanks @jmeistrich
